language: python
python:
    - "3.6"
    - "3.5"
    - "3.4"
before_install:
    - pip install --upgrade pip
    - pip install pipenv
install:
    - pipenv install --dev --deploy
    - pipenv install codecov
    - pipenv check
script:
    - pipenv run pytest -v tests/ --cov=app --cov-report html
after_success:
    - pipenv run codecov
