language: python
python:
    - "3.5"
    - "3.4"
before_install:
    - pip3 install ./sdx-common
install:
    - make build
    - pip install codecov
script:
    - make test
    - coverage run -m unittest tests/*.py
after_success:
    - codecov
