language: python
python:
    - "3.6"
    - "3.5"
    - "3.4"
before_install:
    - pip install --upgrade pip
    - pip install pipenv
install:
    - make build
    - pipenv --three
    - pip install codecov
script:
    - pytest -v tests/ --cov=app --cov-report html
after_success:
    - codecov
