language: python
python:
    - "3.6"
    - "3.5"
    - "3.4"
before_install:
    - pip install --upgrade pip
install:
    - make build
    - pip install pytest-cov 
script:
    - pytest tests/ --cov=app --cov-report html
after_success:
  - bash <(curl -s https://codecov.io/bash)
